# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/denjo/risc/practice/nexys.xdc

# Block Designs: bd/gen_clk/gen_clk.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==gen_clk || ORIG_REF_NAME==gen_clk} -quiet] -quiet

# IP: bd/gen_clk/ip/gen_clk_clk_wiz_0_0/gen_clk_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==gen_clk_clk_wiz_0_0 || ORIG_REF_NAME==gen_clk_clk_wiz_0_0} -quiet] -quiet

# XDC: bd/gen_clk/gen_clk_ooc.xdc
